### PR TITLE
Update ruby version to latest 2.1.5

### PR DESCRIPTION
**Pull request by daniel-ferguson**
Not too important, but there have been a couple of ruby security related updates recently and thought it'd be good set to the newest as a default.

### CODE REVIEW

**Comment by alexclifford** [comment]
Don't forget the new checksum too - https://www.ruby-lang.org/en/news/2014/11/13/ruby-2-1-5-is-released/

**Comment by daniel-ferguson** [comment]
Haha, can't believe I forgot. Sprung to mind just before I checked this thread. Fixed. Checksum seems much shorter than prior one however, am I missing anything?

**Comment by jlund** [comment]
@DanielFerguson Thanks for doing this! The checksum looks shorter because the Ansible `get_url` module uses SHA256 checksums, not MD5. I'll merge this commit and then fix the checksum in a separate one. I'm happy to know that people are using this.

**Comment by daniel-ferguson** [comment]
Now I'm rechecking this, running on vagrant and it's failing. First run was fine with the checksum I submitted a commit with but it's giving me a did not match error, and this `4305cc6ceb094df55210d83548dcbeb5117d74eea25196a9b14fa268d354b100` as the downloaded gzips checksum. Which looks more in line with what was in there before, though out of line with the ruby website provided checksums, and what md5sum tells me.

**Comment by daniel-ferguson** [comment]
Ah you got there first. Thanks for the info!

**Comment by jlund** [comment]
Sure thing! Give it a shot now and it should be working.

**Comment by daniel-ferguson** [comment]
Still find it strange that it worked first time round... Yep! Thank you for the work on these. First day using ansible and overall finding it way more appealing in simplicity for small deployments.
I have a preference for system ruby installs rather than having rbenv/rvm on non-dev systems, it's nice to have it working so smoothly! :)

**Comment by jlund** [comment]
If the file already existed on the server that you were testing on, then the SHA256 checksum comparison would have been skipped.

You're welcome! I'm a huge fan of Ansible and consider it to be the best automation tool currently available. Feel free to email me if you have any questions as you are getting started.

**Comment by daniel-ferguson** [comment]
Thank you!

**Pull request merged**
